brew "git"
brew "gh"
brew "starship"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "neovim"
brew "nvm"
brew "uv"

cask "proton-mail"
cask "proton-pass"
cask "brave-browser"
cask "spotify"
cask "visual-studio-code"
cask "ghostty"
cask "claude-code"
cask "alt-tab"
cask "rectangle"
cask "stats"
cask "linearmouse" # 0 acceleration, 0.5 mouse sens, 32 scroll sens, middle mouse gesture btn

# upscope

brew "lazydocker"
brew "docker-machine"
brew "docker-compose"
brew "docker-credential-helper"
brew "doctl"
brew "watch"
brew "mutagen-io/mutagen/mutagen"
brew "xwmx/taps/hosts"
