services:
    - ControlCenter
    - Dock
    - Finder
    - SystemUIServer

defaults:
    - domain: com.apple.controlcenter
      key: BatteryShowPercentage
      value_type: bool
      value: "true"
      current_host: true

    - domain: NSGlobalDomain
      key: com.apple.swipescrolldirection
      value_type: bool
      value: "false" # requires logout

    - domain: NSGlobalDomain
      key: ApplePressAndHoldEnabled
      value_type: bool
      value: "false" # hold a key to repeat it instead of the accent menu; requires logout

    - domain: NSGlobalDomain
      key: KeyRepeat
      value_type: int
      value: "2" # repeat speed once held (~30ms); requires logout

    - domain: NSGlobalDomain
      key: InitialKeyRepeat
      value_type: int
      value: "15" # delay before repeat starts (~225ms); requires logout


# Manual changes:
#   - Appearance → Icon & widget style → Dark
#   - Displays → Automatically adjust brightness → OFF
#   - Displays → colour profile → Display P3
#   - Menu Bar → remove from menu bar: Spotlight, Focus, Screen Mirroring, Display, Now Playing
#   - Menu Bar → disable all "Allow in the Menu Bar" items
#   - Lock Screen → Turn display off on battery when inactive → 10 min
#   - Lock Screen → Require password after screen saver begins or display is off → Immediately
#   - Keyboard → Keyboard Shortcuts → Screenshots → Copy picture of selected area to the clipboard → ⌥⇧S

# TODO:
# - Finder
# - Spotlight
